# Generated by Django 2.0.2 on 2018-03-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0038_volunteerprogram_volunteer_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprogram',
            name='volunteer_work',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
