# Generated by Django 2.0.2 on 2018-03-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0039_auto_20180316_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprogram',
            name='volunteer_work',
            field=models.CharField(blank=True, default='None', max_length=50, null=True),
        ),
    ]
