# Generated by Django 2.0.2 on 2018-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0040_auto_20180316_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprogram',
            name='spanish_lessons',
            field=models.CharField(blank=True, default='None', max_length=50),
            preserve_default=False,
        ),
    ]
