# Generated by Django 2.0.2 on 2018-03-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0041_auto_20180316_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprogram',
            name='spanish_lessons',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
