# Generated by Django 2.0.2 on 2018-03-16 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0042_auto_20180316_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprogram',
            name='volunteer_work',
        ),
    ]
