# Generated by Django 2.0.2 on 2018-03-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0043_remove_volunteerprogram_volunteer_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprogram',
            name='volunteer_work',
            field=models.CharField(blank=True, null=False, default='None', max_length=50),
        ),
    ]
