# Generated by Django 2.0.2 on 2018-03-06 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=60)),
                ('service_description', models.TextField(max_length=1000)),
                ('levels_open_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Level')),
            ],
        ),
    ]
