# Generated by Django 2.0.2 on 2018-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_level_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='levels_open_to',
        ),
        migrations.AddField(
            model_name='service',
            name='levels_open_to',
            field=models.ManyToManyField(to='enroll.Level'),
        ),
    ]
