# Generated by Django 2.0.2 on 2018-03-06 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_auto_20180306_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('s', 'Student'), ('a', 'Adult'), ('c', 'Child')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Customer_type')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Service')),
            ],
            options={
                'ordering': ['service', 'customer_type'],
            },
        ),
    ]
