# Generated by Django 2.0.2 on 2018-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_auto_20180306_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='customertype',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
