# Generated by Django 2.0.2 on 2018-03-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_customertype_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
