# Generated by Django 2.0.2 on 2018-03-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_auto_20180306_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
