# Generated by Django 2.0.2 on 2018-03-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_auto_20180306_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_start_date', models.DateField()),
                ('course_length', models.PositiveSmallIntegerField(default=1)),
                ('group_number', models.PositiveSmallIntegerField(default=1)),
                ('application_made', models.DateField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Customer')),
                ('course_chosen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Service')),
                ('current_spanish_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Level')),
            ],
            options={
                'ordering': ['-application_made'],
            },
        ),
    ]
