# Generated by Django 2.0.2 on 2018-03-06 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_courseapplication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='AbilityLevel',
        ),
    ]

    atomic = False
