# Generated by Django 2.0.2 on 2018-03-06 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_auto_20180306_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_type', models.CharField(choices=[('h', 'Host Family'), ('s', 'School building'), ('p', 'Private Apartment')], max_length=1)),
                ('room_type', models.CharField(choices=[('c', 'Shared'), ('s', 'Single'), ('d', 'Double'), ('n', 'N/A')], max_length=1)),
                ('catering', models.CharField(choices=[('n', 'None'), ('b', 'Breakfast'), ('h', 'Half-board'), ('f', 'Full-Board')], max_length=1)),
            ],
            options={
                'ordering': ['accommodation_type', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('accommodation_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.AccommodationOption')),
            ],
            options={
                'ordering': ['accommodation_option'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('airport_pickup', models.CharField(choices=[('y', 'Yes'), ('n', 'No')], max_length=1)),
                ('accommodation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.AccommodationOption')),
            ],
        ),
    ]
