# Generated by Django 2.0.2 on 2018-03-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_accommodationoption_accommodationprice_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationoption',
            name='catering',
            field=models.CharField(choices=[('n', 'None'), ('b', 'Breakfast'), ('h', 'Half-board'), ('f', 'Full-Board')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='accommodationoption',
            name='room_type',
            field=models.CharField(choices=[('c', 'Shared'), ('s', 'Single'), ('d', 'Double'), ('n', 'N/A')], default='n', max_length=1),
        ),
    ]
