# Generated by Django 2.0.2 on 2018-03-07 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0015_application_applicant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Nationality',
            new_name='nationality',
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
