# Generated by Django 2.0.2 on 2018-03-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0016_auto_20180307_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default='n', max_length=1),
        ),
    ]
