# Generated by Django 2.0.2 on 2018-03-09 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0017_service_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='course_chosen',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Service'),
        ),
        migrations.AlterField(
            model_name='courseapplication',
            name='current_spanish_level',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.AbilityLevel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
