# Generated by Django 2.0.2 on 2018-03-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0018_auto_20180309_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='extra',
        ),
        migrations.AddField(
            model_name='abilitylevel',
            name='image',
            field=models.ImageField(null=True, upload_to='levels/'),
        ),
        migrations.AddField(
            model_name='abilitylevel',
            name='level_description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('l', 'Lesson'), ('s', 'Special program'), ('e', 'Extra')], default='l', max_length=1),
        ),
    ]
