# Generated by Django 2.0.2 on 2018-03-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0019_auto_20180309_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=80)),
                ('answer', models.CharField(max_length=1000)),
                ('question_type', models.CharField(choices=[('p', 'Planning your trip and arrival'), ('l', 'Spanish lessons'), ('b', 'Booking and payment')], max_length=1)),
            ],
            options={
                'ordering': ['question'],
            },
        ),
        migrations.AlterField(
            model_name='accommodationprice',
            name='duration',
            field=models.CharField(choices=[('d', 'daily'), ('w', 'weekly'), ('m', 'monthly')], max_length=1),
        ),
    ]
