# Generated by Django 2.0.2 on 2018-03-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0021_auto_20180309_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duation_weeks',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='fixed_duration',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='hours',
            field=models.PositiveSmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
