# Generated by Django 2.0.2 on 2018-03-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0022_auto_20180309_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duation_weeks',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ignore if duration is not fixed'),
        ),
        migrations.AlterField(
            model_name='service',
            name='hours',
            field=models.PositiveSmallIntegerField(default=10, help_text='If duration is not fixed, put in hours per week'),
        ),
    ]
