# Generated by Django 2.0.2 on 2018-03-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0023_auto_20180309_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duation_weeks',
            new_name='duration_weeks',
        ),
    ]
