# Generated by Django 2.0.2 on 2018-03-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0024_auto_20180309_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationDescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='accommodation/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
