# Generated by Django 2.0.2 on 2018-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0025_accommodationdescriptions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccommodationDescriptions',
            new_name='AccommodationDescription',
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_type',
            field=models.CharField(choices=[('p', 'Planning your trip and arrival'), ('l', 'Spanish lessons'), ('b', 'Booking and payment'), ('a', 'Accommodation')], max_length=1),
        ),
    ]
