# Generated by Django 2.0.2 on 2018-03-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0026_auto_20180309_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(help_text='(Or quote)', max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teacher/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('testimonial', models.TextField(max_length=800)),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/')),
            ],
        ),
    ]
