# Generated by Django 2.0.2 on 2018-03-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0027_teacher_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=60)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='feature/')),
            ],
        ),
    ]
