# Generated by Django 2.0.2 on 2018-03-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0029_accommodationdescription_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationdescription',
            name='features',
        ),
        migrations.AddField(
            model_name='accommodationdescription',
            name='features',
            field=models.ManyToManyField(to='enroll.Feature'),
        ),
    ]
