# Generated by Django 2.0.2 on 2018-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0030_auto_20180311_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodationoption',
            options={'ordering': ['accommodation_type', 'room_type', 'catering']},
        ),
        migrations.AlterModelOptions(
            name='accommodationprice',
            options={'ordering': ['accommodation_option', 'duration']},
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('l', 'Lesson'), ('s', 'Special program'), ('e', 'Extra'), ('v', 'Volunteer program'), ('c', 'Volunteering & Spanish Lesson')], default='l', max_length=1),
        ),
    ]
