# Generated by Django 2.0.2 on 2018-03-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0031_auto_20180316_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=30)),
                ('image', models.ImageField(null=True, upload_to='projects/')),
                ('level_description', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
