# Generated by Django 2.0.2 on 2018-03-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0033_auto_20180316_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerproject',
            name='project_name',
            field=models.CharField(max_length=45),
        ),
    ]
