# Generated by Django 2.0.2 on 2018-03-16 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0036_auto_20180316_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprogram',
            name='program_type',
            field=models.CharField(choices=[('v', 'Volunteering only'), ('s', 'Spanish plus volunteering')], default='v', max_length=1),
        ),
    ]
