# Generated by Django 2.0.2 on 2018-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0037_volunteerprogram_program_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprogram',
            name='volunteer_work',
            field=models.CharField(blank=True, default='None', max_length=50),
        ),
    ]
