# Generated by Django 2.0.2 on 2019-01-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0039_auto_20190129_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='group_number',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4 or more')], default=1),
        ),
    ]
