# Generated by Django 2.0.2 on 2019-01-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0040_auto_20190129_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication',
            name='current_spanish_level',
            field=models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced'), ('d', 'Different levels')], default='b', max_length=1),
        ),
    ]
