# Generated by Django 2.0.2 on 2019-02-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0041_auto_20190129_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'ordering': ['question_type']},
        ),
        migrations.AddField(
            model_name='service',
            name='service_description_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_description_es',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_en',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_name_es',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
