# Generated by Django 2.0.2 on 2019-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0044_auto_20190208_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_es',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
