# Generated by Django 2.0.2 on 2019-02-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0045_auto_20190209_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name_es',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_en',
            field=models.TextField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='testimonial_es',
            field=models.TextField(max_length=800, null=True),
        ),
    ]
