# Generated by Django 2.0.2 on 2019-02-17 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0046_auto_20190209_0920'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_start_date', models.DateField()),
                ('current_spanish_level', models.CharField(choices=[('b', 'Beginner'), ('i', 'Intermediate'), ('a', 'Advanced'), ('d', 'Different levels')], default='b', max_length=1)),
                ('application_made', models.DateField(auto_now=True)),
                ('applicant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.Customer')),
                ('program_chosen', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enroll.VolunteerProgram')),
            ],
            options={
                'ordering': ['-application_made'],
            },
        ),
    ]
