# Generated by Django 2.0.2 on 2019-02-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0047_volunteerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='first_preference',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='second_preference',
            field=models.CharField(default='none', max_length=40),
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='third_preference',
            field=models.CharField(default='none', max_length=40),
        ),
    ]
