# Generated by Django 2.0.2 on 2019-02-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0048_auto_20190217_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='first_preference',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='second_preference',
        ),
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='third_preference',
        ),
    ]
