# Generated by Django 2.0.2 on 2019-02-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0049_auto_20190217_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerapplication',
            name='current_spanish_level',
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='preferences',
            field=models.CharField(default='No preferences given', max_length=100),
        ),
    ]
