# Generated by Django 2.0.2 on 2019-02-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0050_auto_20190217_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerapplication',
            name='status',
            field=models.CharField(choices=[('s', 'Submitted'), ('a', 'Accepted')], default='s', max_length=1),
        ),
    ]
