# Generated by Django 2.0.2 on 2019-03-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0051_volunteerapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='abilitylevel',
            name='level_description_en',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='abilitylevel',
            name='level_description_es',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='abilitylevel',
            name='level_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='abilitylevel',
            name='level_name_es',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='volunteerapplication',
            name='preferences',
            field=models.CharField(default='No preferences given', max_length=150),
        ),
    ]
