# Generated by Django 2.0.2 on 2019-03-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0055_auto_20190307_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(max_length=60),
        ),
    ]
