# Generated by Django 2.0.2 on 2019-03-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0057_auto_20190307_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question_type',
            field=models.CharField(max_length=40),
        ),
    ]
