# Generated by Django 2.0.2 on 2019-03-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0059_auto_20190310_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('p', 'Prefer not to say')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
