# Generated by Django 2.0.2 on 2019-03-19 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0060_auto_20190311_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date_of_birth_en',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth_es',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_address_en',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_address_es',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name_es',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender_en',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('p', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender_es',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('p', 'Prefer not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_en',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name_es',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status_en',
            field=models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='marital_status_es',
            field=models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='nationality_es',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation_en',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='occupation_es',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number_en',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='passport_number_es',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_en',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_es',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_en',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='whatsapp_es',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
