# Generated by Django 2.0.2 on 2019-03-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0061_auto_20190319_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_of_birth_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_address_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email_address_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='gender_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marital_status_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='marital_status_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='nationality_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='occupation_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='occupation_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport_number_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='passport_number_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_es',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp_en',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='whatsapp_es',
        ),
    ]
