# Generated by Django 2.0.2 on 2019-03-20 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0062_auto_20190319_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(default=datetime.date.today, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email_address',
            field=models.EmailField(max_length=254, verbose_name='email_address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other'), ('p', 'Prefer not to say')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('m', 'Married'), ('s', 'Single')], max_length=1, verbose_name='marital_status'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='nationality',
            field=models.CharField(max_length=15, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='occupation',
            field=models.CharField(blank=True, max_length=30, verbose_name='occupation'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='passport_number',
            field=models.CharField(max_length=12, verbose_name='passport_number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, verbose_name='whatsapp'),
        ),
    ]
